### ISSUE TITLE
"Request entity too large: limit is 3145728" in DO k8s

### ISSUE THREAD

**Issue by kingdun3284** [kintoproj/kinto-helm#14]
**Describe the bug**
When executing "helm upgrade --install kinto --namespace kintohub .", it results in "Request entity too large: limit is 3145728" in DO k8s"

**To Reproduce**
1. Create managed K8s in Digital Ocean
2. Follow the step of kintohub installation (https://www.kintohub.com/getting-started/installation/)
3. Hit this error.

**Comment by bakayolo** [comment]
@kingdun3284 it's fixed. Thanks for reporting.
