### ISSUE TITLE
Warning message appears when installing the helm chart

### ISSUE THREAD

**Issue by nandiheath** [kintoproj/kinto-helm#5]
**Describe the bug**
Warning appears when installing the Kintohub helm chart

```
coalesce.go:196: warning: cannot overwrite table with non table for requests (map[memory:4Gi])
```

**To Reproduce**
1. Checkout the repo
2. Install kintohub following the README 
3. run `helm upgrade --install kinto --namespace kintohub .` and the warning appears

**Expected behavior**
It should not show a warning message

**Desktop (please complete the following information):**
 - Mac OS Catalina

**Comment by bakayolo** [comment]
@nandiheath this does not happen anymore, I fixed it.
We do have other warning though that we need to be careful with because it will become an issue on k8s 1.22
